In [3]:
import tensorflow as tf

## Creating Tensors

- Tensors can be many different data types, for example a float32, int32, string and more
- All tensors have a data type and shape
- They are the main object passed around and manipulated in tf

In [5]:
# basic format is tf.Variable(data, tf.datatype)

string_tensor = tf.Variable('This is a string', tf.string)

integer_tensor = tf.Variable(23, tf.int16)

float_tensor = tf.Variable(2.3, tf.float64)

#These are scalars

#These are rank 0

## Rank / Degree of Tensors

- Number of dimensions invovled in tensor

In [9]:
#Rank 1 tensor, when you have an array it is at least rank 1

#This is because this array can store more than 1 value in 1 dimension  or think of as 1 list

#i.e. it will always have 1 row but can store n columns

rank1_tensor = tf.Variable(['Test'], tf.string)

In [10]:
#Rank 2 tensor

#This is rank 2 because it has a list within a list (this example has two lists in one list)

#The rank of a tensor is the deepest level of a nested list

rank2_tensor = tf.Variable([['test', 'one'], ['test', 'two']], tf.string)  #becomes a matrix

In [12]:
#To determine rank of a tensor, looked at numpy output

tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shapes of Tensors

- just amount of elements in each dimension, like an n x m matrix
- Use .shape to find out shape of a tensor
- NOTE: sometimes the shape may be unknown

In [16]:
rank2_tensor.shape

#Will be [2, 2] since we have 2 lists and both lists have 2 elements inside

TensorShape([2, 2])

## Changing Shape
- Used a lot when working with TF
- When change shape, you have the same number of elements but in a different shape, for example if you have 4 elements in total in a 2x2 matrix, can have a 1x4 matrix instead
- tf.reshape

In [23]:
tensor1 = tf.ones([1, 2, 3])   #the ones() function created a shape [1, 2, 3] tensor with ones in
# an array with 1 list, that contains 2 lists each with 3 elements

tensor2 = tf.reshape(tensor1, [3, 2 , 1])
#an array with 3 lists that each have 2 lists with just 1 element inside

tensor3 = tf.reshape(tensor2, [3, -1])  #using -1 tells tensor to calculate the size of the dimenions in that place, so will reshape tensor to [3, 2]
# so since we have 6 elements, and we specified 3 lists, tensor will calulate that we need 2 elements in each of the three lists

#all three of these tensors have 6 elements

In [19]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [20]:
tensor2

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [21]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

## Types of Tensors

Most common types of tensors include:
- Variable
- Constant     (Immutable)
- Placeholder  (Immutable)
- SpareTensor  (Immutable)

Immutable = value of tensor cannot change during execution

Therefore, only use variable tensor when you think you want to change the value of the tensor

## Evaluating tensors

- This is getting its value
- To evaluate a tensor you need to create a session

There are many ways to do this but simplest is as below

In [24]:
'''

with tf.Session() as sess:  #creates session with default graph
    tensor.eval()       #swap tensor with the name of your own tensor

'''

'\n\nwith tf.Session() as sess:  #creates session with default graph\n    tensor.eval()       #swap tensor with the name of your own tensor\n\n'